<?php
if(function_exists("register_field_group"))
{
    register_field_group(array (
        'id' => 'acf_flexible-content-types',
        'title' => 'Flexible Content Types',
        'fields' => array (
            array (
                'key' => 'field_54c3f3e2fbdd7',
                'label' => 'Content Block',
                'name' => 'fct_content_block',
                'type' => 'flexible_content',
                'layouts' => array (
// Content Types
// === === === === === === === === === === === === ===
                    array (
                        'label' => 'Banner',
                        'name' => 'fct_banner',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54c6e36a62e96',
                                'label' => 'Image',
                                'name' => 'fct_banner_image',
                                'type' => 'image',
                                'column_width' => '',
                                'save_format' => 'object',
                                'preview_size' => 'thumbnail',
                                'library' => 'all',
                            ),
                            array (
                                'key' => 'field_54c6e3a069873',
                                'label' => 'Image URL',
                                'name' => 'fct_banner_image_url',
                                'type' => 'text',
                                'instructions' => 'Setting an image will override this setting',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Split - Text / Text',
                        'name' => 'fct_split_text_text',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54c3f6eb2034d',
                                'label' => 'Left',
                                'name' => 'fct_split_text_text_left',
                                'type' => 'wysiwyg',
                                'column_width' => '',
                                'default_value' => '',
                                'toolbar' => 'full',
                                'media_upload' => 'no',
                            ),
                            array (
                                'key' => 'field_54c3f70f2034e',
                                'label' => 'Right',
                                'name' => 'fct_split_text_text_right',
                                'type' => 'wysiwyg',
                                'column_width' => '',
                                'default_value' => '',
                                'toolbar' => 'full',
                                'media_upload' => 'no',
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Split - Image / Text',
                        'name' => 'fct_split_image_text',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54z3f7399196e',
                                'label' => 'Left',
                                'name' => 'fct_split_image_text_left',
                                'type' => 'image',
                                'column_width' => '',
                                'save_format' => 'object',
                                'preview_size' => 'medium',
                                'library' => 'all',
                            ),
                            array (
                                'key' => 'field_54z3f7209196d',
                                'label' => 'Right',
                                'name' => 'fct_split_image_text_right',
                                'type' => 'wysiwyg',
                                'column_width' => '',
                                'default_value' => '',
                                'toolbar' => 'full',
                                'media_upload' => 'no',
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Split - Text / Image',
                        'name' => 'fct_split_text_image',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54c3f7a2a0z69',
                                'label' => 'Left',
                                'name' => 'fct_split_text_image_left',
                                'type' => 'wysiwyg',
                                'column_width' => '',
                                'default_value' => '',
                                'toolbar' => 'full',
                                'media_upload' => 'no',
                            ),
                            array (
                                'key' => 'field_54c3f7z2a0e6a',
                                'label' => 'Right',
                                'name' => 'fct_split_text_image_right',
                                'type' => 'image',
                                'column_width' => '',
                                'save_format' => 'object',
                                'preview_size' => 'medium',
                                'library' => 'all',
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Full - Text',
                        'name' => 'fct_full_text',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54c3f82cf72a8',
                                'label' => 'Text',
                                'name' => 'text',
                                'type' => 'wysiwyg',
                                'column_width' => '',
                                'default_value' => '',
                                'toolbar' => 'full',
                                'media_upload' => 'yes',
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Full - Text (Large)',
                        'name' => 'fct_full_text_large',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54c83b15d1a6a',
                                'label' => 'Text',
                                'name' => 'text_large',
                                'type' => 'textarea',
                                'instructions' => 'Try and keep this to around one paragraph :)',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'formatting' => 'html',
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Full - Image',
                        'name' => 'fct_full_image',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54c83d1f8104f',
                                'label' => 'Image',
                                'name' => 'fct_full_image_image',
                                'type' => 'image',
                                'column_width' => '',
                                'save_format' => 'object',
                                'preview_size' => 'medium',
                                'library' => 'all',
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Full - Image w/ Lists',
                        'name' => 'fct_full_image_with_lists',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54c3f8fa8b654',
                                'label' => 'Image',
                                'name' => 'fct_full_image_with_lists_image',
                                'type' => 'image',
                                'column_width' => '',
                                'save_format' => 'object',
                                'preview_size' => 'medium',
                                'library' => 'all',
                            ),
                            array (
                                'key' => 'field_54c3f9028b655',
                                'label' => 'Lists',
                                'name' => 'fct_full_image_with_lists_lists',
                                'type' => 'repeater',
                                'column_width' => '',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_54c3fa3a99b09',
                                        'label' => 'Heading',
                                        'name' => 'fct_full_image_with_lists_lists_list_heading',
                                        'type' => 'text',
                                        'column_width' => '',
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'formatting' => 'html',
                                        'maxlength' => '',
                                    ),
                                    array (
                                        'key' => 'field_54c3fa4b99b0a',
                                        'label' => 'Icons',
                                        'name' => 'fct_full_image_with_lists_lists_list_icon',
                                        'type' => 'text',
                                        'column_width' => '',
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'formatting' => 'html',
                                        'maxlength' => '',
                                    ),
                                    array (
                                        'key' => 'field_54c3fa5299b0b',
                                        'label' => 'Items',
                                        'name' => 'fct_full_image_with_lists_lists_list_items',
                                        'type' => 'repeater',
                                        'column_width' => '',
                                        'sub_fields' => array (
                                            array (
                                                'key' => 'field_54c3fa5a99b0c',
                                                'label' => 'List Item',
                                                'name' => 'fct_full_image_with_lists_lists_list_item',
                                                'type' => 'text',
                                                'column_width' => '',
                                                'default_value' => '',
                                                'placeholder' => '',
                                                'prepend' => '',
                                                'append' => '',
                                                'formatting' => 'html',
                                                'maxlength' => '',
                                            ),
                                        ),
                                        'row_min' => '',
                                        'row_limit' => '',
                                        'layout' => 'row',
                                        'button_label' => 'Add List Item',
                                    ),
                                ),
                                'row_min' => '',
                                'row_limit' => '',
                                'layout' => 'row',
                                'button_label' => 'Add List',
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Full - Call to Action',
                        'name' => 'fct_full_call_to_action',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54c3f83ef72a9',
                                'label' => 'Main Heading',
                                'name' => 'fct_full_call_to_action_main_heading',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_54c3f847f72aa',
                                'label' => 'Small Heading ',
                                'name' => 'fct_full_call_to_action_small_heading',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_54c3f89af72ab',
                                'label' => 'Buttons',
                                'name' => 'fct_full_call_to_action_buttons',
                                'type' => 'repeater',
                                'column_width' => '',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_54c3f8b4f72ac',
                                        'label' => 'Text',
                                        'name' => 'fct_full_call_to_action_buttons_text',
                                        'type' => 'text',
                                        'column_width' => '',
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'formatting' => 'html',
                                        'maxlength' => '',
                                    ),
                                    array (
                                        'key' => 'field_54c3f8cbf72ad',
                                        'label' => 'Destination',
                                        'name' => 'fct_full_call_to_action_buttons_destination',
                                        'type' => 'text',
                                        'column_width' => '',
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'formatting' => 'html',
                                        'maxlength' => '',
                                    ),
                                ),
                                'row_min' => '',
                                'row_limit' => 2,
                                'layout' => 'row',
                                'button_label' => 'Add Button',
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Page Links w/ Text',
                        'name' => 'fct_page_links_with_text',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54c6e9a852933',
                                'label' => 'Page Links',
                                'name' => 'fct_page_links_with_text_links',
                                'type' => 'repeater',
                                'column_width' => '',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_54c6e9b452934',
                                        'label' => 'Image',
                                        'name' => 'fct_page_links_with_text_links_image',
                                        'type' => 'image',
                                        'column_width' => '',
                                        'save_format' => 'object',
                                        'preview_size' => 'medium',
                                        'library' => 'all',
                                    ),
                                    array (
                                        'key' => 'field_54c6e9cc52935',
                                        'label' => 'Heading',
                                        'name' => 'fct_page_links_with_text_links_heading',
                                        'type' => 'text',
                                        'column_width' => '',
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'formatting' => 'html',
                                        'maxlength' => '',
                                    ),
                                    array (
                                        'key' => 'field_54c6e9d752936',
                                        'label' => 'Supporting Text',
                                        'name' => 'fct_page_links_with_text_links_text',
                                        'type' => 'textarea',
                                        'column_width' => '',
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'maxlength' => '',
                                        'rows' => '',
                                        'formatting' => 'html',
                                    ),
                                    array (
                                        'key' => 'field_54c6eb8977fdb',
                                        'label' => 'Link',
                                        'name' => 'fct_page_links_with_text_links_link',
                                        'type' => 'page_link',
                                        'column_width' => '',
                                        'post_type' => array (
                                            0 => 'page',
                                        ),
                                        'allow_null' => 1,
                                        'multiple' => 0,
                                    ),
                                    array (
                                        'key' => 'field_54c6ebae77fdc',
                                        'label' => 'Button Text',
                                        'name' => 'fct_page_links_with_text_links_button',
                                        'type' => 'text',
                                        'column_width' => '',
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'formatting' => 'html',
                                        'maxlength' => '',
                                    ),
                                ),
                                'row_min' => '',
                                'row_limit' => '',
                                'layout' => 'row',
                                'button_label' => 'Add Row',
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Work Examples',
                        'name' => 'fct_work_examples',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_55e431e0de57c',
                                'label' => 'Work Posts',
                                'name' => 'fct_work_posts',
                                'type' => 'repeater',
                                'column_width' => '',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_55e433278577a',
                                        'label' => 'Work Post',
                                        'name' => 'fct_work_post',
                                        'type' => 'post_object',
                                        'column_width' => '',
                                        'post_type' => array (
                                            0 => 'all',
                                        ),
                                        'taxonomy' => array (
                                            0 => 'category:51',
                                        ),
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                    ),
                                ),
                                'row_min' => 6,
                                'row_limit' => 6,
                                'layout' => 'table',
                                'button_label' => 'Add Row',
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Gallery',
                        'name' => 'fct_gallery',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_55e4c8c65e127',
                                'label' => 'Gallery',
                                'name' => 'gallery',
                                'type' => 'gallery',
                                'column_width' => '',
                                'preview_size' => 'thumbnail',
                                'library' => 'all',
                            ),
                        ),
                    ),
                ),
                'button_label' => 'Add Content',
                'min' => '',
                'max' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
                array (
                    'param' => 'page_template',
                    'operator' => '!=',
                    'value' => 'template-normal.php',
                    'order_no' => 1,
                    'group_no' => 0,
                ),
            ),
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                    'order_no' => 0,
                    'group_no' => 1,
                ),
            ),
        ),
        'options' => array (
            'position' => 'acf_after_title',
            'layout' => 'no_box',
            'hide_on_screen' => array (
                0 => 'excerpt',
                1 => 'custom_fields',
                2 => 'discussion',
                3 => 'comments',
                4 => 'revisions',
                5 => 'slug',
                6 => 'author',
                7 => 'format',
                8 => 'categories',
                9 => 'tags',
                10 => 'send-trackbacks'
            ),
        ),
        'menu_order' => 0,
    ));
}
